// <auto-generated />
using System;
using CodexAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodexAPI.Migrations
{
    [DbContext(typeof(CodexDbContext))]
    [Migration("20260513153937_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CodexAPI.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 13, 15, 39, 36, 698, DateTimeKind.Utc).AddTicks(5485),
                            Descricao = "Conceitos básicos de programação",
                            Nome = "Fundamentos",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 13, 15, 39, 36, 698, DateTimeKind.Utc).AddTicks(6104),
                            Descricao = "Desenvolvimento web frontend",
                            Nome = "Frontend",
                            Ordem = 2
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 13, 15, 39, 36, 698, DateTimeKind.Utc).AddTicks(6106),
                            Descricao = "Desenvolvimento web backend",
                            Nome = "Backend",
                            Ordem = 3
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 13, 15, 39, 36, 698, DateTimeKind.Utc).AddTicks(6107),
                            Descricao = "DevOps e infraestrutura",
                            Nome = "DevOps",
                            Ordem = 4
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 13, 15, 39, 36, 698, DateTimeKind.Utc).AddTicks(6108),
                            Descricao = "Preparação para certificações",
                            Nome = "Certificações",
                            Ordem = 5
                        });
                });

            modelBuilder.Entity("CodexAPI.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalhes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CodexAPI.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AreaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 13, 15, 39, 36, 699, DateTimeKind.Utc).AddTicks(183),
                            Descricao = "Princípios fundamentais",
                            Nome = "Lógica de Programação",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 13, 15, 39, 36, 699, DateTimeKind.Utc).AddTicks(802),
                            Descricao = "Arrays, Listas, Pilhas",
                            Nome = "Estruturas de Dados",
                            Ordem = 2
                        },
                        new
                        {
                            Id = 3,
                            AreaId = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 13, 15, 39, 36, 699, DateTimeKind.Utc).AddTicks(804),
                            Descricao = "Markup e estilos",
                            Nome = "HTML & CSS",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 4,
                            AreaId = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 13, 15, 39, 36, 699, DateTimeKind.Utc).AddTicks(805),
                            Descricao = "Linguagem do navegador",
                            Nome = "JavaScript",
                            Ordem = 2
                        },
                        new
                        {
                            Id = 5,
                            AreaId = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 13, 15, 39, 36, 699, DateTimeKind.Utc).AddTicks(807),
                            Descricao = "Backend com C#",
                            Nome = "C# & .NET",
                            Ordem = 1
                        });
                });

            modelBuilder.Entity("CodexAPI.Models.ProgressoTopico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Concluido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Progresso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TopicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TopicoId");

                    b.HasIndex("UsuarioId", "TopicoId")
                        .IsUnique();

                    b.ToTable("ProgressosTopicos");
                });

            modelBuilder.Entity("CodexAPI.Models.Topico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoExemplo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dificuldade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Topicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Conteudo = "Aprenda sobre variáveis...",
                            DataCriacao = new DateTime(2026, 5, 13, 15, 39, 36, 699, DateTimeKind.Utc).AddTicks(1340),
                            Dificuldade = 1,
                            DisciplinaId = 1,
                            Ordem = 1,
                            Titulo = "Variáveis e Tipos"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Conteudo = "Operadores aritméticos, lógicos...",
                            DataCriacao = new DateTime(2026, 5, 13, 15, 39, 36, 699, DateTimeKind.Utc).AddTicks(1916),
                            Dificuldade = 1,
                            DisciplinaId = 1,
                            Ordem = 2,
                            Titulo = "Operadores"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Conteudo = "If, else, switch...",
                            DataCriacao = new DateTime(2026, 5, 13, 15, 39, 36, 699, DateTimeKind.Utc).AddTicks(1919),
                            Dificuldade = 2,
                            DisciplinaId = 1,
                            Ordem = 3,
                            Titulo = "Condicionais"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Conteudo = "For, while, do-while...",
                            DataCriacao = new DateTime(2026, 5, 13, 15, 39, 36, 699, DateTimeKind.Utc).AddTicks(1920),
                            Dificuldade = 2,
                            DisciplinaId = 1,
                            Ordem = 4,
                            Titulo = "Laços de Repetição"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Conteudo = "Trabalho com arrays...",
                            DataCriacao = new DateTime(2026, 5, 13, 15, 39, 36, 699, DateTimeKind.Utc).AddTicks(1922),
                            Dificuldade = 2,
                            DisciplinaId = 2,
                            Ordem = 1,
                            Titulo = "Arrays"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Conteudo = "Tags, atributos, semântica...",
                            DataCriacao = new DateTime(2026, 5, 13, 15, 39, 36, 699, DateTimeKind.Utc).AddTicks(1924),
                            Dificuldade = 1,
                            DisciplinaId = 3,
                            Ordem = 1,
                            Titulo = "Introdução ao HTML"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Conteudo = "Variáveis, funções básicas...",
                            DataCriacao = new DateTime(2026, 5, 13, 15, 39, 36, 699, DateTimeKind.Utc).AddTicks(1925),
                            Dificuldade = 1,
                            DisciplinaId = 4,
                            Ordem = 1,
                            Titulo = "Primeiros Passos com JavaScript"
                        });
                });

            modelBuilder.Entity("CodexAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Papel")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("usuario");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CodexAPI.Models.AuditLog", b =>
                {
                    b.HasOne("CodexAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CodexAPI.Models.Disciplina", b =>
                {
                    b.HasOne("CodexAPI.Models.Area", "Area")
                        .WithMany("Disciplinas")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("CodexAPI.Models.ProgressoTopico", b =>
                {
                    b.HasOne("CodexAPI.Models.Topico", "Topico")
                        .WithMany("ProgressosTopicos")
                        .HasForeignKey("TopicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodexAPI.Models.Usuario", "Usuario")
                        .WithMany("ProgressosTopicos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CodexAPI.Models.Topico", b =>
                {
                    b.HasOne("CodexAPI.Models.Disciplina", "Disciplina")
                        .WithMany("Topicos")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("CodexAPI.Models.Area", b =>
                {
                    b.Navigation("Disciplinas");
                });

            modelBuilder.Entity("CodexAPI.Models.Disciplina", b =>
                {
                    b.Navigation("Topicos");
                });

            modelBuilder.Entity("CodexAPI.Models.Topico", b =>
                {
                    b.Navigation("ProgressosTopicos");
                });

            modelBuilder.Entity("CodexAPI.Models.Usuario", b =>
                {
                    b.Navigation("ProgressosTopicos");
                });
#pragma warning restore 612, 618
        }
    }
}
