// <auto-generated />
using System;
using CodexAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodexAPI.Migrations
{
    [DbContext(typeof(CodexDbContext))]
    [Migration("20260516211401_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodexAPI.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icone")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 642, DateTimeKind.Utc).AddTicks(7951),
                            Descricao = "Conceitos básicos de programação",
                            Nome = "Fundamentos",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 642, DateTimeKind.Utc).AddTicks(8704),
                            Descricao = "Desenvolvimento web frontend",
                            Nome = "Frontend",
                            Ordem = 2
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 642, DateTimeKind.Utc).AddTicks(8707),
                            Descricao = "Desenvolvimento web backend",
                            Nome = "Backend",
                            Ordem = 3
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 642, DateTimeKind.Utc).AddTicks(8709),
                            Descricao = "DevOps e infraestrutura",
                            Nome = "DevOps",
                            Ordem = 4
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 642, DateTimeKind.Utc).AddTicks(8710),
                            Descricao = "Preparação para certificações",
                            Nome = "Certificações",
                            Ordem = 5
                        });
                });

            modelBuilder.Entity("CodexAPI.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detalhes")
                        .HasColumnType("text");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CodexAPI.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Imagem")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 642, DateTimeKind.Utc).AddTicks(9500),
                            Descricao = "Princípios fundamentais",
                            Nome = "Lógica de Programação",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(284),
                            Descricao = "Arrays, Listas, Pilhas",
                            Nome = "Estruturas de Dados",
                            Ordem = 2
                        },
                        new
                        {
                            Id = 3,
                            AreaId = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(288),
                            Descricao = "Markup e estilos",
                            Nome = "HTML & CSS",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 4,
                            AreaId = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(290),
                            Descricao = "Linguagem do navegador",
                            Nome = "JavaScript",
                            Ordem = 2
                        },
                        new
                        {
                            Id = 5,
                            AreaId = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(292),
                            Descricao = "Linguagem de programação C#",
                            Nome = "C#",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 6,
                            AreaId = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(295),
                            Descricao = "Framework .NET para aplicações web e desktop",
                            Nome = ".NET",
                            Ordem = 2
                        },
                        new
                        {
                            Id = 7,
                            AreaId = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(297),
                            Descricao = "JavaScript no backend com Node.js",
                            Nome = "JavaScript",
                            Ordem = 3
                        },
                        new
                        {
                            Id = 8,
                            AreaId = 5,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(299),
                            Descricao = "Certificação fundamentals Microsoft Azure",
                            Nome = "AZ-900",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 9,
                            AreaId = 5,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(300),
                            Descricao = "Certificação AI fundamentals Microsoft Azure",
                            Nome = "AI-900",
                            Ordem = 2
                        },
                        new
                        {
                            Id = 10,
                            AreaId = 5,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(303),
                            Descricao = "Certificação GitHub fundamentals",
                            Nome = "GH-900",
                            Ordem = 3
                        },
                        new
                        {
                            Id = 11,
                            AreaId = 5,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(304),
                            Descricao = "Certificação GitHub advanced",
                            Nome = "GH-300",
                            Ordem = 4
                        },
                        new
                        {
                            Id = 12,
                            AreaId = 4,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(306),
                            Descricao = "Sistema de controle de versão distribuído",
                            Nome = "Git",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 13,
                            AreaId = 4,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(307),
                            Descricao = "Plataforma de colaboração e hospedagem de repositórios",
                            Nome = "GitHub",
                            Ordem = 2
                        });
                });

            modelBuilder.Entity("CodexAPI.Models.ProgressoTopico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Concluido")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Progresso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TopicoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TopicoId");

                    b.HasIndex("UsuarioId", "TopicoId")
                        .IsUnique();

                    b.ToTable("ProgressosTopicos");
                });

            modelBuilder.Entity("CodexAPI.Models.Topico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoExemplo")
                        .HasColumnType("text");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Dificuldade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("integer");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Topicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Conteudo = "Aprenda sobre variáveis...",
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(988),
                            Dificuldade = 1,
                            DisciplinaId = 1,
                            Ordem = 1,
                            Titulo = "Variáveis e Tipos"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Conteudo = "Operadores aritméticos, lógicos...",
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(1916),
                            Dificuldade = 1,
                            DisciplinaId = 1,
                            Ordem = 2,
                            Titulo = "Operadores"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Conteudo = "If, else, switch...",
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(1919),
                            Dificuldade = 2,
                            DisciplinaId = 1,
                            Ordem = 3,
                            Titulo = "Condicionais"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Conteudo = "For, while, do-while...",
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(1922),
                            Dificuldade = 2,
                            DisciplinaId = 1,
                            Ordem = 4,
                            Titulo = "Laços de Repetição"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Conteudo = "Trabalho com arrays...",
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(1924),
                            Dificuldade = 2,
                            DisciplinaId = 2,
                            Ordem = 1,
                            Titulo = "Arrays"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Conteudo = "Tags, atributos, semântica...",
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(1927),
                            Dificuldade = 1,
                            DisciplinaId = 3,
                            Ordem = 1,
                            Titulo = "Introdução ao HTML"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Conteudo = "Variáveis, funções básicas...",
                            DataCriacao = new DateTime(2026, 5, 16, 21, 14, 0, 643, DateTimeKind.Utc).AddTicks(1928),
                            Dificuldade = 1,
                            DisciplinaId = 4,
                            Ordem = 1,
                            Titulo = "Primeiros Passos com JavaScript"
                        });
                });

            modelBuilder.Entity("CodexAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("Genero")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("Papel")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("usuario");

                    b.Property<string>("Rua")
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Avatar = "https://i.pravatar.cc/150?img=1",
                            DataAtualizacao = new DateTime(2026, 5, 16, 21, 14, 0, 642, DateTimeKind.Utc).AddTicks(870),
                            DataCriacao = new DateTime(2026, 5, 13, 16, 22, 57, 366, DateTimeKind.Utc),
                            Email = "admin@codex.com.br",
                            Nome = "Admin",
                            Papel = "admin",
                            SenhaHash = "$2a$11$Z9XRi3yU00qWRB5REoBS4OulWR7setX9CC5QmL6VHa1U01K30g1sm",
                            Sobrenome = "Codex"
                        });
                });

            modelBuilder.Entity("CodexAPI.Models.AuditLog", b =>
                {
                    b.HasOne("CodexAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CodexAPI.Models.Disciplina", b =>
                {
                    b.HasOne("CodexAPI.Models.Area", "Area")
                        .WithMany("Disciplinas")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("CodexAPI.Models.ProgressoTopico", b =>
                {
                    b.HasOne("CodexAPI.Models.Topico", "Topico")
                        .WithMany("ProgressosTopicos")
                        .HasForeignKey("TopicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodexAPI.Models.Usuario", "Usuario")
                        .WithMany("ProgressosTopicos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CodexAPI.Models.Topico", b =>
                {
                    b.HasOne("CodexAPI.Models.Disciplina", "Disciplina")
                        .WithMany("Topicos")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("CodexAPI.Models.Area", b =>
                {
                    b.Navigation("Disciplinas");
                });

            modelBuilder.Entity("CodexAPI.Models.Disciplina", b =>
                {
                    b.Navigation("Topicos");
                });

            modelBuilder.Entity("CodexAPI.Models.Topico", b =>
                {
                    b.Navigation("ProgressosTopicos");
                });

            modelBuilder.Entity("CodexAPI.Models.Usuario", b =>
                {
                    b.Navigation("ProgressosTopicos");
                });
#pragma warning restore 612, 618
        }
    }
}
