name: Trigger auto deployment for codex-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/codex-api-AutoDeployTrigger-d1e67784-f642-405e-91c6-416a595cce9f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CODEXAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CODEXAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CODEXAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: codexacr2.azurecr.io
          registryUsername: ${{ secrets.CODEXAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CODEXAPI_REGISTRY_PASSWORD }}
          containerAppName: codex-api
          resourceGroup: codex-rg
          imageToBuild: codexacr2.azurecr.io/codex-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


